#!/bin/bash

# Firebase Web Push Setup Script
# This script helps configure Firebase for web push notifications

echo "=========================================="
echo "Firebase Web Push Notifications Setup"
echo "=========================================="
echo ""
echo "Before running this script, you need to:"
echo "1. Create a Firebase project at https://console.firebase.google.com/"
echo "2. Add a web app to your project"
echo "3. Enable Cloud Messaging"
echo "4. Generate a VAPID key pair"
echo ""
read -p "Have you completed these steps? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Please complete the Firebase setup first."
    echo "See WEB_PUSH_NOTIFICATIONS_SETUP.md for detailed instructions."
    exit 1
fi

echo ""
echo "Please enter your Firebase configuration values:"
echo "(You can find these in Firebase Console → Project Settings → General)"
echo ""

read -p "API Key: " API_KEY
read -p "Auth Domain (e.g., your-project.firebaseapp.com): " AUTH_DOMAIN
read -p "Project ID: " PROJECT_ID
read -p "Storage Bucket (e.g., your-project.appspot.com): " STORAGE_BUCKET
read -p "Messaging Sender ID: " SENDER_ID
read -p "App ID: " APP_ID
echo ""
echo "VAPID Key (from Cloud Messaging → Web Push certificates):"
read -p "VAPID Key: " VAPID_KEY
echo ""
echo "FCM Server Key (from Cloud Messaging → Server key):"
read -p "FCM Server Key: " FCM_SERVER_KEY

# Create config directory if it doesn't exist
mkdir -p src/app/config

# Create firebase config file
echo "Creating firebase.config.ts..."
cat > src/app/config/firebase.config.ts << EOF
// Firebase Configuration for Web Push Notifications
// Generated by setup-firebase-web-push.sh

export const firebaseConfig = {
  apiKey: "$API_KEY",
  authDomain: "$AUTH_DOMAIN",
  projectId: "$PROJECT_ID",
  storageBucket: "$STORAGE_BUCKET",
  messagingSenderId: "$SENDER_ID",
  appId: "$APP_ID"
};

export const vapidKey = "$VAPID_KEY";
EOF

# Create service worker file
echo "Creating firebase-messaging-sw.js..."
cat > src/firebase-messaging-sw.js << EOF
// Firebase Cloud Messaging Service Worker
// Generated by setup-firebase-web-push.sh

importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-messaging-compat.js');

// Initialize Firebase in service worker
firebase.initializeApp({
  apiKey: "$API_KEY",
  authDomain: "$AUTH_DOMAIN",
  projectId: "$PROJECT_ID",
  storageBucket: "$STORAGE_BUCKET",
  messagingSenderId: "$SENDER_ID",
  appId: "$APP_ID"
});

const messaging = firebase.messaging();

// Handle background messages
messaging.onBackgroundMessage((payload) => {
  console.log('[firebase-messaging-sw.js] Received background message:', payload);
  
  const notificationTitle = payload.notification?.title || 'New Message';
  const notificationOptions = {
    body: payload.notification?.body || '',
    icon: '/assets/icon/icon.png',
    badge: '/assets/icon/badge.png',
    data: payload.data,
    tag: payload.data?.chatId || 'default',
    requireInteraction: false
  };

  self.registration.showNotification(notificationTitle, notificationOptions);
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  console.log('[firebase-messaging-sw.js] Notification clicked:', event);
  event.notification.close();
  
  const urlToOpen = event.notification.data?.url || '/';
  
  // Open the app or focus existing window
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUnmanaged: true })
      .then((clientList) => {
        // Check if app is already open
        for (const client of clientList) {
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus();
          }
        }
        // Open new window if not already open
        if (clients.openWindow) {
          return clients.openWindow(urlToOpen);
        }
      })
  );
});
EOF

# Update .env file
echo "Updating .env file..."
if [ -f .env ]; then
    # Backup existing .env
    cp .env .env.backup
    echo "Backed up existing .env to .env.backup"
fi

# Append Firebase config to .env
cat >> .env << EOF

# Firebase Configuration (for web push notifications)
FIREBASE_API_KEY=$API_KEY
FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN
FIREBASE_PROJECT_ID=$PROJECT_ID
FIREBASE_STORAGE_BUCKET=$STORAGE_BUCKET
FIREBASE_MESSAGING_SENDER_ID=$SENDER_ID
FIREBASE_APP_ID=$APP_ID
FIREBASE_VAPID_KEY=$VAPID_KEY
FCM_SERVER_KEY=$FCM_SERVER_KEY
EOF

# Install Firebase SDK
echo ""
echo "Installing Firebase SDK..."
npm install firebase

echo ""
echo "=========================================="
echo "✅ Setup Complete!"
echo "=========================================="
echo ""
echo "Files created:"
echo "  ✓ src/app/config/firebase.config.ts"
echo "  ✓ src/firebase-messaging-sw.js"
echo "  ✓ .env (updated)"
echo ""
echo "Next steps:"
echo ""
echo "1. Update angular.json to include the service worker:"
echo "   Add 'src/firebase-messaging-sw.js' to assets array"
echo ""
echo "2. Update src/app/services/push-notification.service.ts"
echo "   to use Firebase for web push (see WEB_PUSH_NOTIFICATIONS_SETUP.md)"
echo ""
echo "3. Register service worker in src/index.html"
echo "   (see WEB_PUSH_NOTIFICATIONS_SETUP.md for code)"
echo ""
echo "4. Test with: ionic serve"
echo ""
echo "5. Grant notification permission when prompted"
echo ""
echo "For detailed instructions, see:"
echo "  - WEB_PUSH_NOTIFICATIONS_SETUP.md"
echo "  - PUSH_NOTIFICATIONS_SETUP.md"
echo ""
